[preface]
== Introduction

The GeoPackage Standards Working Group (SWG) has identified a need for the ability to store tiled gridded elevation data in a GeoPackage. This capability will be used to support use cases such as the following:

*	Visualization
**	2D (hillshade, color relief, slope)
**	3D (supporting changing view angles and level of detail)
*	Analysis
**	Viewshed and line-of-sight
** Cross-country mobility (off-road routing)
** Site suitability and planning (slope analysis such as helicopter landing zones)
** 3D geometry representations of features (ground-based, airspace)
**	Terrain association (associating images to mapped locations)
**	Augmented reality training

This document describes an extension to the OGC GeoPackage Encoding Standard which leverages the existing structure for raster tiles using PNG or TIFF files as the container for the elevation values themselves. This capability was designed to be relatively easy to implement and to be suitable for a wide variety of computing environments including the mobile/handheld computing environment. We acknowledge that this approach will not support certain applications that require a high degree of precision and/or accuracy (e.g., targeting).
